storage:
    storageMethod: yaml
    yaml:
        dataFile: data\data.yml
    mysql:
        host: localhost
        database: Minecraft
        username: username
        password: password
        port: 3306
    sqlite:
        dataFile: data\data.sqlite
settings:
    combat:
        disablePlayerCollision: true
        playerRespawnImmunity: 0
        pvpLogger: false
        pvpLoggerDuration: 15
        gainedLost: 20
    world:
        disableWeatherChange: false
        disableBlockPlace: false
        disableBlockDestroy: false
        disableCreatureSpawn: true
        disableExplosionDestroy: false
    defaultKit: "KIT_NAME_HERE"
messages:
version: 1.0
