storage:
    storageMethod: sqlite
    yaml:
        dataFile: data\data.yml
    mysql:
        host: localhost
        database: Minecraft
        username: username
        password: password
        port: 3306
    sqlite:
        dataFile: data\data.sqlite
settings:
    combat:
        disablePlayerCollision: true
        playerRespawnImmunity: 0
        pvpLogger: false
        pvpLoggerDuration: 15
        gainedLost: 20
    chat:
        chatFormatting: false
    defaultKit: "KIT_NAME_HERE"
    debugMode: false
messages:
    join-message-broadcast: "&a%player% has joined the battlefield"
    quit-message-broadcast: "&c%player% has left"
    quit-message-combat-log-broadcast: "&c%player% is a sore loser and left while in combat"
    correct-usage-message: "&cCorrect usage: &7/%commandName% %usage%"
    no-permission-message: "&cYou don't have permission perform this action"
    unknown-kit-message: "&cUnknown kit '%kitName%'"
    kit-given-message: "&aYou have received the '%kitName%' kit"
    kit-created-message: "&aThe kit '%kitName%' has been created!"
    kit-deleted-message: "&aThe kit '%kitName' has been deleted!"
    kit-already-exists-message: "&cA kit by that name already exists"
    kit-permission-nodes-unique-message: "&cKit permission nodes must be unique"
    invalid-permission-node: "&cInvalid permission node"
    combat-kit-change-message: "&cYou cannot change your kit whilst in combat."
    player-death-message: "&c%player% has died!"
    player-death-private-message: "&cYou have been slain by %killer% and lost %lostPoints% points"
    player-killed-private-message: "&aYou have killed %player% and gained %gainedPoints% points"
    player-slain-message: "&c%player% has been slain by %killer%"
    player-kill-streak-ended-message: "&c%player%'s kill streak of %killStreak% was brought to a fatal end by %killer%"
    leaderboard-format: "&6%position%. %user% with %points% points"
    invalid-spawn-id-message: "&cPlease enter a valid spawn id"
    spawn-saved-message: "&aSpawn set!"
    spawn-deleted-message: "&cSpawn deleted!"
    player-not-found-message: "&c%player% was not found"
    player-stats-reset-message: "&a%player%'s stats have been reset"
    player-stats-heading: "&7---- &3%player%'s stats &7----"
    player-stats-format: "&6%statistic%: %value%"
    player-stats-footer: "&7---- ---- ---- ----"
    chat-format: "[%group%] %player%: %message%"
    spectator-enabled-message: "&aSpectator mode has been enabled."
    spectator-disabled-message: "&cSpectator mode has been disabled"
    spectator-in-combat-message: "&cYou cannot enable spectator mode if you have been in combat."
    no-permission-while-spectating: "&cYou cannot perform this action whilst in Spectator mode."
    banned-command-message: "&cThis command is banned during Combat"
version: 2.23
