name: FreeForAll
version: 2.0-Alpha
main: me.angrypostman.freeforall.FreeForAll
description: "Free for all, fight in a battle to become the number one"
author: AngryPostman

commands:
    stats:
    resetstats:
    kit:
    savekit:
    setspawn:
    delspawn:
    leaderboard:
        aliases: [top, records]
permission:
    freeforall.*:
        default: op
        children:
            freeforall.command.*: true
    freeforall.command.*:
        default: op
        children:
            freeforall.command.stats: true
            freeforall.command.stats.viewOther: true
            freeforall.command.resetstats: true
            freeforall.command.kit: true
            freeforall.command.savekit: true
            freeforall.command.setspawn: true
            freeforall.command.delspawn: true